### ISSUE TITLE
Edit feature creating duplicates

### ISSUE THREAD

**Issue by johnnypacia** [johnnypacia/wiki#1]
Hi Anna, 

When a user submits an update to a song(article) it creates a new song rather than update the existing one. I've tried "patch" and "delete" requests as well as trying to delete the song in the post request using song.destory. In all cases it still duplicates. Here's the current state of my server.rb:

```
post "/songs/:id" do
      song = Song.find(params["id"])
      song.update({title: params[:title], edit_id: params[:edit_id], content: params[:content]})
      # edit = Edit.create({user_id: session[:user_id], edit_content: params[:content], date_edited: DateTime.now})
      redirect to "/songs/#{song.id}"
    end
```

What else can I try to prevent the post from adding extra songs to the database?

**Comment by annarankin** [comment]
Hey Johnny, I'm not at home right now, but I'll check this out tonight.

**Comment by johnnypacia** [comment]
Thanks Anna!

**Comment by annarankin** [comment]
Hey Johnny, I took a look at your `edit_song.erb` form - looks like it's posting to `/songs`:

``` html
<form method="POST" action="/songs">
```

You're actually never hitting the `/songs/:id` route handler in your server!

**Comment by johnnypacia** [comment]
Thanks again for your help here and in class today!
