### ISSUE TITLE
date_edited value not working in erb

### ISSUE THREAD

**Issue by johnnypacia** [johnnypacia/wiki#2]
Hi Anna, 

The "last version added" feature isn't working on my song.erb. Originally I was getting an error so I changed my song.rb model to include a definition accounting for edits. Here's snippets of what I have for that: 

```
class Song < ActiveRecord::Base
    belongs_to :category
    belongs_to :user
    has_many :edits
    def last_version_date 
        if edits.last 
            edits.last.date_edited 
        else 
            date_created
        end 
    end 
end
```

And for my song.erb:

```
<h1><%= @song.title %></h1>
<p>written by: <%= @song.user.name %></p>
<p>contact email: <%= @song.user.email %></p>
<p><%= @song.content %></p>
<p>created at: <%= @song.date_created %></p>
<p>last version added: <%= @song.last_version_date %></p>
</p>
```

Now, even if I've made edits it still shows the original creation date under "last version added", so the first part of the def I created in my model isn't working for some reason.  Do you have any ideas about why this may be happening?

**Comment by annarankin** [comment]
Hey Johnny, have you tried this out in Pry? You might try changing your method like so:

``` ruby
class Song < ActiveRecord::Base
    belongs_to :category
    belongs_to :user
    has_many :edits
    def last_version_date 
        if self.edits.last 
            self.edits.last.date_edited 
        else 
            self.date_created
        end 
    end 
end
```

You're defining an instance method, so this method should be able to refer back to the instance it's being called on.

**Comment by johnnypacia** [comment]
Still getting the same error even after updating that.

**Comment by johnnypacia** [comment]
Anything else I can try to get this feature working?

**Comment by phlco** [comment]
Johnny, when you're getting an error that information is IMPORTANT! Tell us what the error is! Paste it in and let us soak it up!

**Comment by johnnypacia** [comment]
I hear that, but I don't get a formal error here. Instead, the value of <%= @song.last_version_date %> is always just the date the song was created. In other words, the first half of the def below in my model isn't working: 

```
 if self.edits.last 
            self.edits.last.date_edited 
        else 
            self.date_created
        end 
```

**Comment by annarankin** [comment]
Hey Johnny, I downloaded and ran your code - none of your edits are related to your songs!

When you create your edit in your server, do you ever tell it what song it belongs to?

**Comment by johnnypacia** [comment]
Yes, I've added that here: 

```
Edit.create({user_id: session[:user_id], song_id: params[:song_id], edit_content: params[:content], date_edited: DateTime.now})
```

It's still showing the date created

**Comment by annarankin** [comment]
Gotcha - can you push the latest version of your code?

**Comment by johnnypacia** [comment]
Yes, I went ahead and did that. Though what I currently have doesn't work. I'm just trying out different options.

**Comment by phlco** [comment]
What's the status here? Are you getting an error?

**Comment by johnnypacia** [comment]
Fixed it! updates are registering properly. I was looking for params[:id] but my .create had params[:song_id] and that was what was causing the error. 

Thanks for all your help guys!

**Comment by phlco** [comment]
Great job!
